version: "3"
services:
  react-app:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - 80:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
